server:
  port: 8079
taskflow:
  tcp:
    port: 5080
  filesys:
    rootpath: /home/chen/

spring:
  datasource:
    url: jdbc:mysql://mysqlserver.com:3306/chen_dev?useUnicode=true&autoReconnect=true&characterEncoding=UTF-8&allowMultiQueries=true
    username: esns
    password: minxing123
mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    location: classpath:mybatis-conf.xml