server:
  port: 8079
taskflow:
  tcp:
    port: 5080

spring:
  datasource:
    url: jdbc:mysql://mysqlserver.com:3306/chen_dev?useUnicode=true
    username: esns
    password: minxing123
mybatis:
  mapperLocations: classpath:mapper/*.xml
